//
//  Vogellist.swift
//  KinderRätsel
//
//  Created by Karlheinz on 25.08.24.
//

import Foundation

// Liste aller verfügbaren Vogelbilder im Assets-Ordner "Vögel"
let allBirdImages = [
    "Vögel/Amsel",
    "Vögel/Bachstelze",
    "Vögel/Bergfink",
    "Vögel/Bienenfresser",
    "Vögel/Birkenzeisig",
    "Vögel/Bläshuhn",
    "Vögel/Blaukehlchen",
    "Vögel/Blaumeise",
    "Vögel/Bluthänfling",
    "Vögel/Braunkehlchen",
    "Vögel/Buchfink",
    "Vögel/Buntspecht",
    "Vögel/Eichelhäher",
    "Vögel/Eisvogel",
    "Vögel/Elster",
    "Vögel/Erlenzeisig",
    "Vögel/Feldlerche",
    "Vögel/Feldsperling",
    "Vögel/Gartenbaumläufer",
    "Vögel/Gartenrotschwanz",
    "Vögel/Gebirgsstelze",
    "Vögel/Gimbel",
    "Vögel/Girlitz",
    "Vögel/Goldammer",
    "Vögel/Graureiher",
    "Vögel/Grauschnäper",
    "Vögel/Grauspecht",
    "Vögel/Grünfink",
    "Vögel/Grünspecht",
    "Vögel/Habicht",
    "Vögel/Haubenlerche",
    "Vögel/haubenmeise",
    "Vögel/Haubentaucher",
    "Vögel/Hausrotschwanz",
    "Vögel/Haussperling",
    "Vögel/Höckerschwan",
    "Vögel/Jagdfasan",
    "Vögel/Kanadagans",
    "Vögel/Kernbeiser",
    "Vögel/Kibitz",
    "Vögel/Kleiber",
    "Vögel/Kleinspecht",
    "Vögel/Kohlmeise",
    "Vögel/Kolkrabe",
    "Vögel/Kuckuck",
    "Vögel/Löffelente",
    "Vögel/Mauerseegler",
    "Vögel/Mäusebussard",
    "Vögel/Mehlschwalbe",
    "Vögel/Neuntöter",
    "Vögel/Nilgans",
    "Vögel/Pirol",
    "Vögel/Rabenkrähe",
    "Vögel/Rauchschwalbe",
    "Vögel/Rotkehlchen",
    "Vögel/Rotmilan",
    "Vögel/Schwanzmeise",
    "Vögel/Schwarzmilan",
    "Vögel/Schwarzschwan",
    "Vögel/Schwarzspecht",
    "Vögel/Seidenreiher",
    "Vögel/Silberreiher",
    "Vögel/Singdrossel",
    "Vögel/Sperlingskauz",
    "Vögel/Star",
    "Vögel/Steinkauz",
    "Vögel/Stiglitz",
    "Vögel/Stockente",
    "Vögel/Storch",
    "Vögel/Sumpfmeise",
    "Vögel/Tannenmeise",
    "Vögel/Türkentaube",
    "Vögel/Turmfalke",
    "Vögel/Wachholderdrossel",
    "Vögel/Waldbaumläufer",
    "Vögel/Wasseramsel",
    "Vögel/Weißstorch",
    "Vögel/Wendehals",
    "Vögel/Zaunkönig",


    // Füge hier weitere Vogelbilder hinzu, die in deinem Assets-Ordner gespeichert sind
]
